# Sets user-defined palette
palette = "dragon"



[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[î˜¿](green) â¯](yellow)"
error_symbol = "[[ï‘§](red) â¯](red)"
vimcmd_symbol = "[â®](green)"


[os]
disabled = false

[os.symbols]
Pop = "ğŸ§ª "

[username]
show_always = true
style = "bold red"
format = '[$user](bold red) '

[directory]
truncation_length = 4
# Catppuccin 'lavender'
style = "bold green"
format = "[$path]($style) "

[git_branch]
symbol = 'ğŸŒ± '
style = 'bold cyan'
format= 'on [$symbol$branch(:$remote_branch)]($style) '

[git_commit]
format = '[\($hash$tag\)]($style) '
commit_hash_length = 7
tag_symbol = 'ğŸ”– '
only_detached = false

[python]
symbol = " ğŸ"
style = "bold bred"
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "â¬¢"
format = '| [$symbol $version](bold bgreen) '

[bun]
symbol = "ğŸ” "
format = ' | [$symbol($version )](bold byello)'

[palettes.dragon]
black ="#0D0C0C"           # Black (Host)
red ="#C4746E"           # Red (Syntax string)
green ="#8A9A7B"           # Green (Command)
yello ="#C4B28A"           # Yellow (Command second)
blue ="#8BA4B0"           # Blue (Path)
magenta ="#A292A3"           # Magenta (Syntax var)
cyan ="#8EA4A2"           # Cyan (Prompt)
white ="#C8C093"           # White
bblack ="#A6A69C"           # Bright Black
bred="#E46876"           # Bright Red (Command error)
bgreen="#87A987"           # Bright Green (Exec)
byello="#E6C384"           # Bright Yellow
bblue ="#7FB4CA"           # Bright Blue (Folder)
bmagenta ="#938AA9"           # Bright Magenta
bcyan ="#7AA89F"           # Bright Cyan
bwhite="#C5C9C5"           # Bright White
bg ="#181616"   # Background
fg ="#C5C9C5"   # Foreground (Text)
cu ="#C8C093" # Cursor

python_icon = "ğŸ"
nodejs_icon = "â¬¢"
bun_user = "ğŸ”"

